### PR TITLE
fix page issues

### PR DESCRIPTION
**Pull request by anmode**
## Related Issue

Closes: #[issue number]

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Review by Isha988 — APPROVED** [review]
I think we should have only redirecting part in `useRedirectIfAuthenticated` function and google signup part in another function. (It is not mandatory to do this)

Rest everything looks good to me.

**Comment by anmode** [comment]
> I think we should have only redirecting part in `useRedirectIfAuthenticated` function and google signup part in another function. (It is not mandatory to do this)
> 
> Rest everything looks good to me.

I fixed... thanks for notifying me. have a look : https://github.com/anmode/grabtern-frontend/pull/580 I hope I addressed.

**Comment by anmode** [comment]
Ahh.. my changes lost... VS code sucks.. do not save file automatically..

**Comment by Isha988** [comment]
> > I think we should have only redirecting part in `useRedirectIfAuthenticated` function and google signup part in another function. (It is not mandatory to do this)
> > Rest everything looks good to me.
> 
> Thanks for notifying me. have a look : #580 I hope I addressed.

Perfect

**Pull request merged**
