### PR TITLE
Date Picker in session booking page

### PR DESCRIPTION
**Pull request by Isha988**
Added Date picker in session booking page.

### CODE REVIEW

**Comment by Isha988** [comment]
Preview

https://github.com/anmode/grabtern-frontend/assets/89572340/fcfc4701-1ccd-448d-9538-6682aa74896f

**Comment by anmode** [comment]
Screenshot 2023-10-29 at 9 22 06 PM
First of all an we this UI! please. it looks good

2nd on clicking date , the time is not showing on frontend (split time)

**Comment by Isha988** [comment]
> Screenshot 2023-10-29 at 9 22 06 PM First of all an we this UI! please. it looks good
> 2nd on clicking date , the time is not showing on frontend (split time)

1. I will fix the ui
2. Okay, I was not aware with split time, I will do

**Comment by Isha988** [comment]
Done,  @anmode please check it out once and let me know if any changes needed.

**Comment by Isha988** [comment]
And I don't no why but prettier is not working in my system for this repo, else it is working fine for other codes

**Comment by anmode** [comment]
I am getting some runtime error:
Screenshot 2023-10-30 at 10 21 44 PM
Screenshot 2023-10-30 at 10 22 44 PM


2nd please make change now in backend and send date from here instead of day, now we will store date in book session db not the day! Rest is cool

**Comment by Isha988** [comment]
> I am getting some runtime error:

Would you please tell how to regenerate these errors ?

**Comment by Isha988** [comment]
> 2nd please make change now in backend and send date from here instead of day, now we will store date in book session db not the day! Rest is cool

Ok

**Comment by anmode** [comment]
> > I am getting some runtime error:
> 
> Would you please tell how to regenerate these errors ?

just try to book the session! you will get the error.. these are undefined error and NULL value case

**Comment by anmode** [comment]
> > 2nd please make change now in backend and send date from here instead of day, now we will store date in book session db not the day! Rest is cool
> 
> Ok

please make sure to change in dashboard which is in user Dash and mentor dash

**Comment by Isha988** [comment]
@anmode please check once, fixed the loadig issue
I haven't get https://user-images.githubusercontent.com/88332977/279135387-2f2bd6db-d9f2-412c-ad53-c10003bf27ca.png error

**Pull request merged**
