### PR TITLE
Validation of The Footer Subscribe button

### LINKED ISSUE #820: 🐞 [BUG] - Working of The Footer Subscribe button
### Description

When button is Clicked it should either send some error  or the Success warning but it just shows a loading circle that might me the case that the button logic is not there  

### Current behaviour

Doesn't return anything other than Loading circle  

### Expected behaviour

Should Return some Error or Success Warning and should be working 

### Reproduction steps

```bash
1. Go to 'Footer of the Website'
2. Click on 'Subscribe button'
4. See the Loading Circle
```

### Screenshots

Video :
[Screencast from 2023-12-13 08-01-54.webm](https://github.com/anmode/grabtern-frontend/assets/85656999/197c8a87-9077-4b03-bd69-8d0b57774242)

### Logs

_No response_

### Browsers

Chrome

### OS

Linux

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

### PR DESCRIPTION
**Pull request by Hemant2335**
## Related Issue

Closes: #820 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
|
Screenshot from 2023-12-13 17-16-40
| 
Screenshot from 2023-12-13 17-17-16
|

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
Looks good! Just pass CI test please ----> prettier

**Comment by anmode** [comment]
`npx prettier --write`

**Comment by Hemant2335** [comment]
Thank you , Now that test has been passed please check

**Comment by anmode** [comment]
Thanks Hemant! your point will be added....

**Pull request merged**
