### PR TITLE
feat: Dashboard tour for users and mentors in mobile view

### PR DESCRIPTION
**Pull request by rishuraj1**
## Related Issue

followup: #806 

## Description of Changes

- added: optimised feature of dashboard tour for mobile devices

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

image

image

image

image

image

@anmode 

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
All looks good Rishu, here are some couple fixes it would be great if you can complete this in PR ( last PR to get merge for swagkit) You have done many descent contribution to grabtern. we are very greatful :)

1.  pending and completed both!
Screenshot 2023-11-07 at 1 23 54 PM
  this need to be fixed in desktop and mobile view 


2.  We need to implement a frontend button in session ( so mentor can delete the session too, backend is prepared and here is the funtcion too  you just need to create a button 
Screenshot 2023-11-07 at 1 28 00 PM

```
const deleteSession = async function (sessionID) {
    try {
      setLoadingState({ status: true });
      setErrorState({ status: false });
  
      // Show a confirmation dialog
      const confirmed = window.confirm("Are you sure you want to delete this session?");
      
      if (!confirmed) {
        // User canceled the deletion
        setLoadingState({ status: false });
        return;
      }
  
      const url = `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/mentors/deleteListedSession/${sessionID}`;
      const response = await axios.delete(url, { withCredentials: true });
  
      fetchData();
      setLoadingState({ status: false });
    } catch (error) {
      setLoadingState({ status: false });
      if (
        error.response &&
        error.response.status >= 400 &&
        error.response.status <= 500
      ) {
        setErrorState({ status: true, message: error.response.data.message });
      } else {
        setErrorState({ status: true });
      }
    }
  };
  ```

4. Edit form session needs some icons!

**Comment by rishuraj1** [comment]
sure, will do it by tonight

**Comment by anmode** [comment]
Cool !

**Comment by rishuraj1** [comment]
@anmode  I am thinking of creating another new table component to display the data, because the UI will break at some point and can't be done using css only. we can use packages like tanstack react table to implement this, since it will take time, I will do it in the next PR. 
Now I have done all the changes requested. additionally, added cancel button to the add and edit session forms.

Screenshot 2023-11-07 161019

Screenshot 2023-11-07 160407

https://github.com/anmode/grabtern-frontend/assets/47839626/f81b75c2-6ba6-41e6-87b3-cd611c8f7f9d

**Comment by anmode** [comment]
> @anmode I am thinking of creating another new table component to display the data, because the UI will break at some point and can't be done using css only. we can use packages like tanstack react table to implement this, since it will take time, I will do it in the next PR. Now I have done all the changes requested. additionally, added cancel button to the add and edit session forms.
> 
> Screenshot 2023-11-07 161019 Screenshot 2023-11-07 160407
>  GrabTern._.Grab.Your.Internship.-.Brave.2023-11-07.16-22-47.mp4

totally agreed! Wow all things looks good.. I'll merge after testing today for sure!

**Comment by anmode** [comment]
Screenshot 2023-11-07 at 9 24 00 PM
Small issue chat bot is over riding the more button , 
1.This issue needs to be fixed and please could you align the items in more option and one fix here is that when we click on any tab in more , the more popup do not closes automatically.

Rest all seems fine

**Comment by rishuraj1** [comment]
@anmode these changes should do the fix.

https://github.com/anmode/grabtern-frontend/assets/47839626/c57465ce-fa28-4355-9ed6-5b9edaaffd27

**Review by anmode — APPROVED** [review]
Cool. LGTM

**Pull request merged**
