### PR TITLE
Newlogo

### PR DESCRIPTION
**Pull request by GitWiz01**
## Related Issue

Closes: #[issue number]

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

Here is the figma file - https://www.figma.com/file/XpucXJaLsHHXjfXEZsRHLV/Grabtern_logo?type=design&node-id=0%3A1&mode=design&t=QUszbT43odDufrp2-1

Group 1

Grabtern_logo (1)
Grabtern_logo

Grabtern_logo (2)

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
cool @GitWiz01 ... this is a huge change.. I will forward this request to the product design dept..

**Comment by GitWiz01** [comment]
Thank you @anmode 
If you have any related work concerning UI/UX
I will be happy to help🤞

**Comment by GitWiz01** [comment]
@anmode have you confirmed with the team?
Please update me if any changes need to be done

**Comment by anmode** [comment]
I did! ... They said logo to be freezed for some time... btw we are open to any design change in website... Sorry for delayed response

**Comment by GitWiz01** [comment]
@anmode Can you merge this pr...please
Surely I will contribute to the site
Thank you for the opportunity 😊✌️



> I did! ... They said logo to be freezed for some time... btw we are open to any design change in website... Sorry for delayed response

**Pull request closed without merging**
