### PR TITLE
doc: Add social links

### LINKED ISSUE #784: 📚 [Documentation / WorkFlow] - Add social links in readme ( with nice icons)
### Description ✍️

Here is discord: https://discord.gg/9zRCUmUtA2
linkedin: https://www.linkedin.com/company/grabtern/
website: www.grabtern.com

and backend url: api.grabtern.com

add insta icon too.. I'll provide link soon!

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

### PR DESCRIPTION
**Pull request by ghoshvidip26**
## Related Issue

Closes: #784 

## Description of Changes

Social Icons in ReadMe.md

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by ghoshvidip26** [comment]
Screenshot 2023-10-22 at 09 42 42

**Comment by ghoshvidip26** [comment]
I'll work on it since the icons aren't visible in GitHub. 
Please give some time.

**Comment by ghoshvidip26** [comment]
Screenshot 2023-10-22 at 14 18 12

@anmode Now check.

**Comment by anmode** [comment]
cool! @Vidip-Ghosh

**Comment by anmode** [comment]
Vidip see readme got disturbed...and these icons do not act as invite link please see

**Comment by ghoshvidip26** [comment]
> Vidip see readme got disturbed...and these icons do not act as invite link please see

Okay looking into it.

**Pull request merged**
