### PR TITLE
Feat: Displayed important errors 

### LINKED ISSUE #783: 🚀 [Feature Request] - Improve error handling ( UX work)
### Is your feature request related to a problem ? Please describe. ✍️

We had not consider all case and error response...  
we have Taostify to display error/success.
you just have to work on all cases frontend can display error which can be shown by frontend.. 

### Describe briefly how you would implement this enhancement.

```bash
for eg:
If any field is blank , it should be show error.
The thing is to consider all possible case of error so user can get what causing error. 
Major area: form filling
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

### PR DESCRIPTION
**Pull request by rishuraj1**
## Related Issue

Closes: #783 

## Description of Changes
- handled/displayed errors via toast popups

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

image

image

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Review by anmode — COMMENTED** [review]
Rishu point is we do not want show Successful message like as User logged in: as it clear that state is updated and user will already get acknowledge...but here we have to make sure to caught and display error. All possible cases. 
We will show sucess message where there is need to get acknowlege.. 
for eg we fill the form here we want to success message but in loggin in dashboard we do not need..

I think you got the idea would like to implement? we will make this PR for `error handling and toastify correction`

**Comment by rishuraj1** [comment]
@anmode okay yes I get the idea, also I have done that in login, registration form...

**Comment by anmode** [comment]
> @anmode okay yes I get the idea, also I have done that in login, registration form...

cool, but i see you show sucess message but that's not needed....as user got acknowlegde as state changed so there is no need to show a sucess message

**Comment by rishuraj1** [comment]
@anmode  ok, I will remove those success notifications and just focus on errors generating while filling form, or performing some other API related work and if there is an error, will show the notification to the user `err message`

**Comment by anmode** [comment]
> @anmode ok, I will remove those success notifications and just focus on errors generating while filling form, or performing some other API related work and if there is an error, will show the notification to the user `err message`

yeah! we will show success messsage where they are really required as "while session booking"

**Comment by anmode** [comment]
@rishuraj1, please be mindful not to perform a force push. Force pushing results in the loss of the entire commit history, and I won't be able to retrieve your previous changes either.

**Comment by rishuraj1** [comment]
@anmode yeah, I discarded my commits purposely because there were many conflicts and I wanted to start fresh...😅

**Pull request closed without merging**
