### PR TITLE
Fix readmefile

### LINKED ISSUE #784: 📚 [Documentation / WorkFlow] - Add social links in readme ( with nice icons)
### Description ✍️

Here is discord: https://discord.gg/9zRCUmUtA2
linkedin: https://www.linkedin.com/company/grabtern/
website: www.grabtern.com

and backend url: api.grabtern.com

add insta icon too.. I'll provide link soon!

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

### PR DESCRIPTION
**Pull request by ghoshvidip26**
## Related Issue

Closes: #784 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by ghoshvidip26** [comment]
Right now please wait. Once completed, I will ping

**Comment by ghoshvidip26** [comment]
Bhai, maine pehle html wale method se kiya tha a href & img lekin usse nhi hua. 
Koi code kaam nhi kr rha hai.

**Comment by ghoshvidip26** [comment]
> Bhai, maine pehle html wale method se kiya tha a href & img lekin usse nhi hua. Koi code kaam nhi kr rha hai.

@anmode

**Comment by ghoshvidip26** [comment]
@anmode Please check now.

**Comment by anmode** [comment]
Just resolve the conflicts vidip and it seems good to merge!

**Comment by ghoshvidip26** [comment]
> Just resolve the conflicts vidip and it seems good to merge!

I've solved the conflicts.

**Pull request merged**
