### PR TITLE
fix the magic url form

### PR DESCRIPTION
**Pull request by anmode**
cc @Isha988

### CODE REVIEW

**Comment by Isha988** [comment]
@anmode please checkout the latest changes

**Comment by anmode** [comment]
Hey @Isha988 all look good,
can you please fix the mentorList, there is some error ig and also required the loader till all mentor list being fetched!
I see your productivity is awesome!! Cool

**Comment by Isha988** [comment]
> Hey @Isha988 all look good, can you please fix the mentorList, there is some error ig and also required the loader till all mentor list being fetched!

okay

**Comment by anmode** [comment]
Cool, nice productivity.

**Pull request merged**
