### PR TITLE
FEATURE: Dark mode

### LINKED ISSUE #778: 🚀 [Feature Request] - Implementing Dark Mode
### Is your feature request related to a problem ? Please describe. ✍️

 i want to implement dark mode using tailwind css and next themes to the web app under Hacktoberfest.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

### PR DESCRIPTION
**Pull request by vatsalsinghkv**
## Related Issue 

Implementation of dark mode

Closes: #778 

## Description of Changes

- Added CSS variables for dark theme in `gloabals.css`.
- Created a `use-theme` hook with context for using themes.
- Wrote logic for storing current mode in local storage.
- Changed the component's hardcoded colour with dark theme CSS variables

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

### CODE REVIEW

**Comment by anmode** [comment]
Nice to see this pR:  Firstly we need to have light theme on default
Some minor UI issues needs to fixed:
Screenshot 2023-11-03 at 11 09 32 AM
Screenshot 2023-11-03 at 11 09 57 AM

and try to login into dashboard see for UI in dark mode there.... Rest all is good!

**Comment by vatsalsinghkv** [comment]
@anmode what do you think we invert this image in the dark mode?
Screenshot 2023-11-03 at 4 15 40 PM

**Comment by vatsalsinghkv** [comment]
@anmode I've tried to login but i didn't get verification email, do you have any testing login credentials for me to test out the dashboard

**Comment by anmode** [comment]
> @anmode I've tried to login but i didn't get verification email, do you have any testing login credentials for me to test out the dashboard

please see readme... all dev emails goes to ethereal. you can find credentials to login into ethereal from readme! and yeah invert image look good!

**Comment by vatsalsinghkv** [comment]
@anmode is there a way to run google auth through the backend endpoints given in the `.env`, I tried loging in manually it didn't work got internal server error. But I fixed more pages like reset password, mentor registration pages to the darkmode in the last commit

**Comment by anmode** [comment]
> @anmode is there a way to run google auth through the backend endpoints given in the `.env`, I tried loging in manually it didn't work got internal server error. But I fixed more pages like reset password, mentor registration pages to the darkmode in the last commit

if you want to login , through email you can login in dev mode but can't use google auth. Due to security purpose we can't to out the client ID. no worries you can create account! 

wait please give me. your credentials which you created for your grabtern dev account?

**Comment by anmode** [comment]
Till time just do one thing in this PR make light theme to be default and I'll merge this pR!

**Review by anmode — APPROVED** [review]
Looks good to merge! Rest more pages you can carry on next PRs. Till time I will get your credentials and will try to see where is the problem arising acctually. 
only last change in this pR to make the default to light theme

**Comment by vatsalsinghkv** [comment]
@anmode sure, we can implement dark-mode on dashboard in the next PR, I think I've made the default theme as `light` in last commit, test it by deleting `darkMode` from local storage and refresh the page. Also while implementing dark-mode I've seen some UI visual errors should I fix them under this PR or should I create another issue for it?

**Comment by anmode** [comment]
Ok you can create next PR!..
can you give me your credentials so i can check what causing err to create grabtern account?

**Comment by vatsalsinghkv** [comment]
@anmode My account is working with production server, but with the demo server I am unable to login, it usually says my account is registered and password don't match. It while resetting it gives a server error, can you try creating an account and resetting its password with the demo server?

My credentials were:
email: `vatsalsinghkv@gmail.com`
password: `i dont know` or `idontknow`

**Comment by anmode** [comment]
oh yeah i see actually demo backend was not updated with mainstream so it ws causing the issue... so i fixed, your password is `idontknow`
I see some pages needs rework in , i think you are mentioning those UI fix.. one main is loader in darkmode will be differenct.

**Pull request merged**
